/*Manager*/

CREATE DATABASE manager;

CREATE TABLE user(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) UNIQUE,
	TELEFONE VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	UF VARCHAR(2) NOT NULL,
	GENERO NOT NULL

);


